// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfREIh9jZYtj1k8sZvpqjXDodnyVbpanA',
    appId: '1:1018193641818:web:36e8ae26a33ec45ec33363',
    messagingSenderId: '1018193641818',
    projectId: 'bee-store-app',
    authDomain: 'bee-store-app.firebaseapp.com',
    databaseURL: 'https://bee-store-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bee-store-app.appspot.com',
    measurementId: 'G-JW969SJ4YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBfhLVVqvCbYO6su0oiQAL0M7Aobd9Og',
    appId: '1:1018193641818:android:3fa836d55fec07d1c33363',
    messagingSenderId: '1018193641818',
    projectId: 'bee-store-app',
    databaseURL: 'https://bee-store-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bee-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfFjCpp1O9QkBwB-rljRYO4UL0yTw60c0',
    appId: '1:1018193641818:ios:d4704689526110adc33363',
    messagingSenderId: '1018193641818',
    projectId: 'bee-store-app',
    databaseURL: 'https://bee-store-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bee-store-app.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfFjCpp1O9QkBwB-rljRYO4UL0yTw60c0',
    appId: '1:1018193641818:ios:f8b3f5899e5b5279c33363',
    messagingSenderId: '1018193641818',
    projectId: 'bee-store-app',
    databaseURL: 'https://bee-store-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bee-store-app.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
